### PR TITLE
Miscellaneous improvement

### PR DESCRIPTION
**Pull request by vide**
- Make managing external java package optional
- Make takipi installation idempotent (it was reinstalling takipi on every puppet run)

### CODE REVIEW

**Comment by pmoust** [comment]
Thanks a lot, you are right in that the the takipi module should not handle the Java dep itself (unless asked to).
Please update the documentation as well.
👍

**Comment by pmoust** [comment]
LGTM

/ping @chook

**Comment by chook** [comment]
Thanks. I believe the re-installing was in order to fetch the latest and greatest. 
In the new approach, how would one upgrade (reinstall) Takipi?

**Comment by vide** [comment]
Well, updating doesn't work in any case under CentOS, because `ensure => installed` instead of `ensure => latest` (actually in my case a `yum upgrade takipi` didn't work neither, I had to remove it manually and then execute puppet). Anyway if you already know what files are created _only_ by `takipi-setup-package` script, I can put it as `creates =>`

**Comment by pmoust** [comment]
Ref #1

**Comment by vide** [comment]
@pmoust @chook so? :) I mean, double-checking what the RPM installs, with the `creates =>` I've added in this PR, the exec won't never be executed, and I understand it is critical to configure the licence. So, what file should I check? I cannot have takipi setup executed **EVERY TIME** puppet is run (every 30 min in my case)

**Comment by pmoust** [comment]
IMHO your PR is fine, and updating the agent is out of scope of this PR.

Adding `ensure => latest` capabilities to fix #1 belongs in another PR.

**Comment by chook** [comment]
Missed #1 ! (Damn honeymoon). I agree with @pmoust . we'll fix upgrading in another day.

**Comment by vide** [comment]
@pmoust but as I said I've just realized that now the `exec {'install takipi': }` will not run at any time, not even on first Takipi install :( So I was asking what file should I check

**Comment by vide** [comment]
I think that I could check for the presence of the actual secret key in `/opt/takipi/work/secret.key` to fix it

**Comment by pmoust** [comment]
Yep.

**Comment by vide** [comment]
Sorry for the commits noise :( Last commit works 100% fine in my installation

**Comment by vide** [comment]
ping @pmoust @chook are you going to merge my PR? do you need anything else?

**Comment by chook** [comment]
@vide I'll verify the PR on our puppet test env next week and if all goes well merge. Thanks!

**Comment by vide** [comment]
ping? :)

**Comment by chook** [comment]
Verified! Thanks!

**Pull request merged**
